# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Product' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Product
  pod 'SCLAlertView', '~> 0.8'
  pod 'Alamofire', '~> 5.8'
  pod 'SDWebImage', '~> 5.18'
  pod 'ProgressHUD', '~> 13.8.6'
  pod 'ImageSlideshow', '~> 1.9'
  pod 'ImageSlideshow/SDWebImage', '~> 1.9'
  pod 'SQLite.swift', '~> 0.14'
  pod 'TextFieldEffects', '~> 1.6'
  pod 'ImagePicker', :git => 'https://github.com/hyperoslo/ImagePicker.git'
  #pod 'ImagePicker', '~> 3.2.0'
  

end
